# Generated by Django 2.2.4 on 2021-02-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='note',
            field=models.CharField(default='old', max_length=255),
            preserve_default=False,
        ),
    ]
